### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by NicolasDumoulin** [tdihp/osrm-c#1]
Hi,
I'm interested to try your wrapper, but I can't built it.
I've compiled the last version of osrm-backend, and I try then to built your package by linking to the osrm-backend/build directory (containing the file "libosrm.pc"):

```
$ PKG_CONFIG_PATH="../osrm-backend/build/" scons
scons: Reading SConscript files ...
Package libosrm was not found in the pkg-config search path.
Perhaps you should add the directory containing `libosrm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libosrm' found
OSError: 'pkg-config libosrm --cflags --libs' exited 1:
  File "osrm-c/SConstruct", line 20:
    exports=['osrm_version', 'osrm_c_version', 'install_prefix'])
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 609:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 546:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "osrm-c/build/SConscript", line 25:
    env.ParseConfig('pkg-config libosrm --cflags --libs')
  File "/usr/lib/scons/SCons/Environment.py", line 1554:
    return function(self, self.backtick(command))
  File "/usr/lib/scons/SCons/Environment.py", line 596:
    raise OSError("'%s' exited %d" % (command, status))
```

What's wrong?
Thank you

**Comment by tdihp** [comment]
Hi. Thanks for your feedback :)

I've only tried to build osrm-c against installed versions of osrm-backend.

For your particular problem, I think it's because of the relative path, Since SCons will execute in the build directory, it may change dir. Would you please try use abs path?

```
PKG_CONFIG_PATH="$PWD/osrm-backend/build/" scons
```

**Comment by tdihp** [comment]
Ahh, now I see why: SCons will strictly control env variables, so `PKG_CONFIG_PATH` won't pass to `pkg-config`.

Can you install osrm-backend by `sudo make install`? For the time being it's possibly the easiest way to get a working build.

**Comment by NicolasDumoulin** [comment]
Ok. I will try with an installed OSRM server.
Thank you!
