### ISSUE TITLE
Compilation issue with last revision of osrm-backend

### ISSUE THREAD

**Issue by NicolasDumoulin** [tdihp/osrm-c#3]
Some changes has been done in osrm-backend and now osrm-c doesn't compile anymore.

**Comment by tdihp** [comment]
Thanks for mentioning, I'll take a look.

**Comment by tdihp** [comment]
I've pushed a branch [feature/backend-v4.9.0](https://github.com/tdihp/osrm-c/tree/feature/backend-v4.9.0), it should work with the current osrm-backend master. I'll make a release later.

**Comment by tdihp** [comment]
The change is released.
