### ISSUE TITLE
How we can fetch GeoJSON results from route response

### ISSUE THREAD

**Issue by srimaln91** [tdihp/osrm-c#4]
Hi,

I want to get the route as a GeoJSON string. Is there a way to accomplish this?

I would be really grateful if someone can help me with this.

Thanks.

**Comment by tdihp** [comment]
Hi srimaln91,

Sorry for the late reply.

Soon After I finished this project, the upsteam project OSRM had a massive overhaul of the API design. Unfortunately I don't have time to keep up with the OSRM project. So this project is no longer compatible with the current versions of OSRM.

You can use the official OSRM c++ API or the Node.js API, or use the rest API from the OSRM site/application, which ever suits you best.
